name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write
  pull-requests: write
  actions: read
  packages: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the package
        run: mvn --batch-mode -DskipTests package

      - name: Run the unit tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List target directory
        run: ls -l target

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push the Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          VERSION=$(echo $GITHUB_SHA | cut -c1-7)
          
          docker build -t $IMAGE_ID:latest -t $IMAGE_ID:$VERSION --file Dockerfile .
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION
